//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSWEBAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public Nullable<int> KisiID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string UrunAd { get; set; }
        public Nullable<byte> UrunMiktar { get; set; }
        public Nullable<short> UrunFiyat { get; set; }
        public Nullable<short> ToplamSepet { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public int SepetID { get; set; }
        public List<Urunler> UrunlerList { get; set; }
        public virtual Kisiler Kisiler { get; set; }
        public virtual Siparisler Siparisler { get; set; }
        public virtual Urunler Urunler { get; set; }
       
    }

}
